name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual runs of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: mattzewdie/2048:latest  # Update this to your Docker Hub repository

    - name: Log out from Docker Hub
      run: docker logout
